### PR TITLE
better dim printing as tuple

### LINKED ISSUE #261: printing of Tuple(Dims) is too verbose
```
julia> dims(X)
(Lat{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float64}, Points}, Dict{String, Any}}(-89.5:1.0:89.5, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float64}, Points}(Ordered{ForwardIndex, ForwardArray, ForwardRelation}(ForwardIndex(), ForwardArray(), ForwardRelation()), Regular{Float64}(1.0), Points()), Dict{String, Any}("units" => "degrees_north", "_FillValue" => -999.0)), Lon{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, 
Regular{Float64}, Points}, Dict{String, Any}}(-179.5:1.0:179.5, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float64}, Points}(Ordered{ForwardIndex, ForwardArray, ForwardRelation}(ForwardIndex(), ForwardArray(), ForwardRelation()), Regular{Float64}(1.0), Points()), Dict{String, Any}("units" => "degrees_east", "_FillValue" => -999.0)))
```

while 

image

is how they are printed when printing the full dim array. Perhaps would be nice to have this kind of printing for tuple of dims?

I'd do a small pr that simply uses `DimensionalData._layout_dims`, but I actually don't know which show method to extend... `::NTuple{<:Dimension}` is not the correct one.

### PR DESCRIPTION
**Pull request by Datseris**
Closes #261

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks, I nearly did that but had to stop somewhere!

Can you run `Documenter.doctest(DimensionalData; fix=true)` to fix the doc test change that's throwing the error?

**Comment by Datseris** [comment]
If you're asking me to put a docstring to the extention of Base.show, which is the only thing that is going on in this PR, then I don't think this makes much sense. The original docstring is appropriate.

**Comment by rafaqz** [comment]
No you just have a failing doc test,

**Comment by rafaqz** [comment]
bump

**Comment by Datseris** [comment]
sorry, fixing the `jlddocs` will have to wait until I have some ample free time, at the moment its not high on my priority list

**Comment by rafaqz** [comment]
No problem, whenever you have time. But it's literally just running that code that's required, I wasn't asking for any manual changes.

**Comment by Datseris** [comment]
I understand, but I didn't even had this package out for development, and did the change on GitHub directly. Nevertheless, running the doctests doesn't work when checking out this PR:
```
julia> Documenter.doctest(DimensionalData; fix=true)
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
┌ Warning: could not find code block in source file
└ @ Documenter.DocTests C:\Users\datse\.julia\packages\Documenter\bFHi4\src\DocTests.jl:408
┌ Warning: could not find code block in source file
└ @ Documenter.DocTests C:\Users\datse\.julia\packages\Documenter\bFHi4\src\DocTests.jl:408
┌ Error: Doctesting failed
│   exception =
│    BoundsError: attempt to access Tuple{} at index [0]
│    Stacktrace:
│      [1] getindex(t::Tuple, i::Int64)
│        @ Base .\tuple.jl:29
│      [2] _layout_dims(io::IOContext{IOBuffer}, mime::MIME{Symbol("text/plain")}, dims::Tuple{})
│        @ DimensionalData ~\.julia\dev\DimensionalData\src\show.jl:137
│      [3] show(io::IOContext{IOBuffer}, mime::MIME{Symbol("text/plain")}, dims::Tuple{})
│        @ DimensionalData ~\.julia\dev\DimensionalData\src\show.jl:208
│      [4] #invokelatest#2
│        @ .\essentials.jl:708 [inlined]
│      [5] invokelatest
│        @ .\essentials.jl:706 [inlined]
```
(stacktrace is huge, I've truncated it)

**Comment by ali-ramadhan** [comment]
Is there any way I can contribute to this PR?

I notice that the `Datseris:patch-1` fork:branch has been deleted.

**Comment by Datseris** [comment]
Sorry about that. Unfortunately one has to spend time fixing all of the "jldoctest" strings, which I do not find as useful as _run_ documentation online via `@example` docs, so I didn't do it... Feel free to take the PR code and start an new PR.

**Comment by ali-ramadhan** [comment]
No worries, thanks for opening this PR. I'll see if I can fix the doctests in a new PR.

**Comment by rafaqz** [comment]
Thanks @ali-ramadhan

**Pull request closed without merging**
