### PR TITLE
new vitepress docs

### PR DESCRIPTION
**Pull request by lazarusA**
build docs locally:

Install Node dependencies: 

```shell
DimensionalData> npm i
```
then install Julia dependencies

```shell
cd docs
```

type

```shell
julia
```
activate 

```shell
] activate .
```

add packages: 

```shell
] add https://github.com/LuxDL/DocumenterVitepress.jl.git
```

```shell
] add Documenter
```
```shell
] dev ../
```

then generate docs by running the `make.jl` file.

Then run a live server from the main directory, namely

```shell
DimensionalData> npm run docs:dev 
```

### CODE REVIEW

**Comment by lazarusA** [comment]
Some previews: 

Screenshot 2024-02-07 at 23 32 25
Screenshot 2024-02-07 at 23 32 48

**Comment by lazarusA** [comment]
please, delete gh-pages branch. No need it anymore. And then active deployment from main on gh-pages, please.
Screenshot 2024-02-13 at 23 54 05

**Comment by rafaqz** [comment]
Whaaa how dies that work?

**Comment by lazarusA** [comment]
what? nothing is failing now if I ignore dead links :D

**Comment by rafaqz** [comment]
Ok so what do I need to do?

**Comment by rafaqz** [comment]
Heres the logo:

**Pull request merged**
