### PR TITLE
Build docs on latest Julia release

### PR DESCRIPTION
**Pull request by sethaxen**
Currently the docs are being built on the LTS. This PR changes to build the docs for the latest Julia release.

### CODE REVIEW

**Comment by rafaqz** [comment]
Should we do both?

**Comment by sethaxen** [comment]
Is that possible? I've never seen it. I don't think it's necessary though. It would be better to add admonitions indicating when a method is only available for certain Julia versions or when behavior changes between versions.

**Comment by rafaqz** [comment]
You can just add another line with `- 1` instead of replacing `- 1.6`, and it will run both.

Its good to test 1.6 for use cases where people are stuck with LTS. They do exist. And we should check for LTS compatible syntax. When `NamedTuple` destructing came I broke the previous LTS in some of my packages by mistake, because the new syntax is nice and you want to used it.

**Comment by sethaxen** [comment]
Ah, I thought you were asking whether we should _deploy_ docs on both LTS and latest release. Sure, we can build docs on both. I'll just need to add a way to disable deployment for v1.6, because otherwise one will overwrite the other.

**Comment by rafaqz** [comment]
Ahh yeah that makes sense, I also didn't totally think through what I was saying with deployment of both docs. Actually having two versions will break the docstests because the `show` output changes.

But building on 1.6 and leaving it there was a conscious choice to force the docs to work on LTS - which means they also work on 1.9. The other way around means they will work on 1.9 but may not work on 1.6.

I chose the conservative option where the docs are less likely to be wrong for any users. But the tradeoff to use the latest syntax may also be valid.

**Comment by rafaqz** [comment]
Ok I'm sold after trying to build docs in the other PR...

**Review by rafaqz — APPROVED** [review]

**Pull request merged**
