### PR TITLE
rm icon links

### PR DESCRIPTION
**Pull request by lazarusA**
as less as possible content in landing page. Minimalist hero page.

Same component as in Tyler.jl, which is working.

### CODE REVIEW

**Comment by asinghvi17** [comment]
It's probably not the icon links - GeometryOps and SwarmMakie work fine without them, and so did DocumenterVitepress.  My bet is that it's some other change...

**Comment by lazarusA** [comment]
Yes, indeed is none of them. Now, all missing things are fixed, including the `ico` file. 
Also, I tested the following cached files:

Screenshot 2024-04-05 at 21 04 57

they are not getting updated after each new released tag. They should, we need to find a way to clear these files from the cache and generated new ones, the correct ones. It should be an option for `vite` in the config file.... at the moment I don't know how. I will need to look into it.

**Comment by rafaqz** [comment]
Should we merge this?

**Comment by lazarusA** [comment]
is just small fixes. So, yes merging is ok.

**Pull request merged**
