### PR TITLE
Maybe Breaking (?): add missing IteratorSize method for dimensions

### PR DESCRIPTION
**Pull request by rafaqz**
Tiny fix so that comprehensions over dimensions return a DimArray. @kapple19 I think this might be even nicer than what you were looking for.

```julia
julia> [(x, y) for x in X(1:5), y in Y(1:3)]
╭─────────────────────────────────────╮
│ 5×3 DimArray{Tuple{Int64, Int64},2} │
├─────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────── dims ┐
  ↓ X Sampled{Int64} 1:5 ForwardOrdered Regular Points,
  → Y Sampled{Int64} 1:3 ForwardOrdered Regular Points
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 ↓ →  1        2        3
 1     (1, 1)   (1, 2)   (1, 3)
 2     (2, 1)   (2, 2)   (2, 3)
 3     (3, 1)   (3, 2)   (3, 3)
 4     (4, 1)   (4, 2)   (4, 3)
 5     (5, 1)   (5, 2)   (5, 3)
```
~~Needs a test.~~ See #820

### CODE REVIEW

**Comment by kapple19** [comment]
That's awesome! Does it work for arbitrary dimensions as per my example?

**Comment by rafaqz** [comment]
Yeah, should work for anything you put in there. It could have worked for years now if I remembered to add that method :sweat_smile:

**Comment by rafaqz** [comment]
This could be considered breaking as its changing the return value of a _lot_ of things

**Comment by kapple19** [comment]
Just to be clear, will the following syntax work?

```
F = DimArray(f(a, b, c) for a in a_vec, b in b_vec, c in c_vec)
```

or do I need to declare my arbitrary `Dim`s?

**Comment by rafaqz** [comment]
Sorry theres not really any way for that to work as is! Its too ambiguous, it would need a macro and those a best saved for when they're really needed. Wrapping with dimensions is what makes all the magic here work because we then own its methods that control the outcomes of a lot of Base julia functions.

So you wont need the `DimArray`, but you need these clunky wrappers. 

```julia
F = [f(a, b, c) for a in Dim{:a}(a_vec), b in Dim{:b}(b_vec), c in Dim{:c}(c_vec)]
```

I always wonder if we should bite the bullet and export `D` as a shortcut to `Dim`, so it would be:

```julia
F = [f(a, b, c) for a in D{:a}(a_vec), b in D{:b}(b_vec), c in D{:c}(c_vec)]
```

Of course you can also do:
```julia
@dim A
@dim B
@dim C
F = [f(a, b, c) for a in A(a_vec), b in B(b_vec), c in C(c_vec)]
```

**Comment by kapple19** [comment]
> Sorry theres not really any way for that to work as is!

That's okay! I understand why, but the existing (prospective) syntax is fine for me since it means I don't have to define multiple intermediate stages, and can instantiate a `DimArray` in one nice swoop.

I can't seem to download the branch, but I'm in no rush, and am looking forward to the merge! Thanks heaps!

**Comment by rafaqz** [comment]
Check your network connection, your just not getting through to github ;)

**Comment by kapple19** [comment]
> I always wonder if we should bite the bullet and export `D` as a shortcut to `Dim`

I am of the opinion that, no. People can just `using DimensionalData: Dim as D`.

Personally I do a lot of `using ... as ...` because I'm pedantic about names. E.g. I always do

```
using DimensionalData: dims as getdims
```

because I like my functions to be verbal, so I would

```
dims = getdims(v::DimArray)
```

**Comment by rafaqz** [comment]
> `dims = getdims(v::DimArray)`

:laughing: yes I clearly have an aversion to putting  `get` on anything, something about it reminds me of OOP days, or its just not aesthetically pleasing. But it would solve a lot, I constantly need to do `DD.dims` inside functions because `dims` is such a common keyword name. But `dims(x)` just looks so much nicer !

**Comment by rafaqz** [comment]
Ohh someone is firewalling something for you! how lucky. I guess `using DimensionalData` is not actually pining github, but julia specific servers

**Comment by kapple19** [comment]
> yes I clearly have an aversion to putting `get` on anything, something about it reminds me of OOP days, or its just not aesthetically pleasing.

I get it. I have similar traumas with MATLAB and its version of OOP. From their case style naming conventions to... everything else.

And don't stress about it, I'm happy to `dims as getdims` 😊.

**Comment by asinghvi17** [comment]
Github was a bit spotty earlier, that might have been the source of your issues.  It should be fine now though so you could try adding the branch again @kapple19

**Comment by kapple19** [comment]
What about the following syntax?

```
V = DimArray(f(a, b) for a in Dim{:a}(1:10), b in Dim{:b}(1:5); name = :V)
```

Is it possible to make that work? The Syntax errors, so is available 👀🥺

**Comment by kapple19** [comment]
Ah I see.

The `DimArray` accepting a generator would, as per my example in the other thread (which I should close to uniquely scope to this thread), bypass the need to construct the `DimArray` with a generator and then `remake` it to assign a `name` value. Especially in motivation for [interop with AlgebraOfGraphics](https://github.com/rafaqz/DimensionalData.jl/issues/821).

**Comment by rafaqz** [comment]
If you use a square brackets generator it will work. But yes we could also accept an uncollected generator.

**Pull request merged**
