### PR TITLE
AlgebraOfGraphics documentation

### PR DESCRIPTION
**Pull request by kapple19**
I got carried away writing examples 😅 was quite fun.
Not considered polished yet.
I've left some lines commented out, noting anything not working.
Some things will have to follow up on AoG like colormap not passing.
Other things are scoped by DD like #823.

I wasn't sure if you'd want to publish examples in the docs asap which would mean changing my examples to work on the latest DimensionalData and AlgebraOfGraphics tags.
Let me know if so, and I can change my examples and remove the `docs/Project-v1.11.toml` file which helped me demonstrate your new method for enabling `Dim`s in array comprehensions.

Local docs build produces a lot of docs errors from other Markdown files... as far as I could see. The stack traces were overpopulating my REPL. Running my code blocks directly to the REPL works.

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks! No rush, I won't be able to review this until November

**Comment by lazarusA** [comment]
yes, plus, maybe we should wait also for https://github.com/rafaqz/DimensionalData.jl/pull/823, so that things are really integrated.

**Comment by kapple19** [comment]
> Thanks! No rush, I won't be able to review this until November

Ah, plenty of time for me to refine examples then 😛

**Comment by asinghvi17** [comment]
FYI, #823 is ready now, so we can probably look at rebasing this PR on top of that one.

One comment about that - could you provide some motivation for the examples?  Maybe a paragraph or so.  I don't really understand what they're meant to do on a cursory read through, and maybe some comments during data construction could be useful too.

The examples do look very cool though!

**Comment by kapple19** [comment]
I think I'll have some time tonight to have a look and make better docs. Thanks so much!

**Comment by lazarusA** [comment]
you example looks like something field-specific, physics. If it doesn't go here, we could always added it to [BeautifulMakie](https://beautiful.makie.org/dev/).

**Comment by kapple19** [comment]
Yeah okay, I'll do that.

**Pull request closed without merging**
