### PR TITLE
fix deploy docs

### PR DESCRIPTION
**Pull request by lazarusA**
@rafaqz this should fix the docs deploy, and possibly the `stable` redirect issue ~ 90% confidence 😓 .

### CODE REVIEW

**Comment by asinghvi17** [comment]
@lazarusA want to push a tag on this commit to test?

**Comment by lazarusA** [comment]
mmm... the deploy was cancelled due to the one happening in master. I will retry later.

**Comment by rafaqz** [comment]
I can also just merge? About to bump a version anyway

**Comment by lazarusA** [comment]
yes, please. Merge.

**Review by asinghvi17 — APPROVED** [review]

**Pull request merged**
