### PR TITLE
Add `eachslice` support post-1.9 for DimStacks and DimArrays

### PR DESCRIPTION
**Pull request by ParadaCarleton**

### CODE REVIEW

**Comment by ParadaCarleton** [comment]
There doesn't seem to be any consensus around how to get backwards compatibility for the new slices; I'm just going to wait until 1.9 before I work on this any more.

**Comment by ParadaCarleton** [comment]
@rafaqz I'm noticing `dims` is type-unstable, and this causes problems. Is there any way to fix this? Presumably functions that reduce across dimensions (e.g. `mean` with a `dims` argument) are type-stable for `DimArrays`, the way they are for regular arrays, but I'm not sure how that could be dealt with.

**Comment by rafaqz** [comment]
`dims` is pretty widely used, some cases may be unstable but many are not. I would need an example to know what you mean.

**Comment by ParadaCarleton** [comment]
``> `dims` is pretty widely used, some cases may be unstable but many are not. I would need an example to know what you mean.

The relevant type instability is in the tests (in methods.jl), and in the newly-added `eachslice` method. The major problem here is that  when a `DimArray` has dimensions of several different types, anything that changes the number of dimensions depending on an argument (e.g. `reduce`, `mapslices`, `eachslice`, etc.) is type-unstable, because the choice of dimension to reduce or slice along affects the type.

**Comment by ParadaCarleton** [comment]
@rafaqz so, this is weird, I just realized `slicedims` is type-stable even though `dims` isn't. Do you know why that is?

**Comment by rafaqz** [comment]
I still don't get what you mean by "dims is type unstable". I really need a MWE pasted here... Because it isn't in a lot of cases or every thing I do all day would be super slow. 

Normally it compiles away as you say.

There are some circumstances where using a runtime Int or Symbol in `dims` will cause stability problems. Some new instabilities may have crept in too, I would like to know where if they have!

But we really need to discuss a specific bit if code to get any answers for you.

**Comment by ParadaCarleton** [comment]
> I still don't get what you mean by "dims is type unstable". I really need a MWE pasted here... Because it isn't in a lot of cases or every thing I do all day would be super slow.
> 
> Normally it compiles away as you say.
> 
> There are some circumstances where using a runtime Int or Symbol in `dims` will cause stability problems. Some new instabilities may have crept in too, I would like to know where if they have!
> 
> But we really need to discuss a specific bit if code to get any answers for you.

MWE:
```
julia> x = X('a':'d')
X 'a':1:'d'

julia> y = Y(10:10:40)
Y 10:10:40

julia> ti = Ti(1:4)
Ti 1:4

julia> a = rand(rng, (-12):12, 4, 4, 4)
4×4×4 Array{Int64, 3}:
[:, :, 1] =
 -11    8   -7   2
   2  -12  -12   1
  -5  -12    2  -2
  -6    3    3  -7

[:, :, 2] =
  0   -9   3    8
 12  -11   0  -10
  0    9  -5  -10
 -3   -3  -6   10

[:, :, 3] =
  0   2   -9   12
 -3  -5   -5   -9
 -2  10  -10   -3
 10  12  -11  -12

[:, :, 4] =
  3  -11  -3   4
 -6   -8  -5  -4
  0    9  -7  -1
 -4    4  -6   0

julia> da = DimArray(a, (x, y, ti))
4×4×4 DimArray{Int64,3} with dimensions: 
  X Categorical{Char} 'a':1:'d' ForwardOrdered,
  Y Sampled{Int64} 10:10:40 ForwardOrdered Regular Points,
  Ti Sampled{Int64} 1:4 ForwardOrdered Regular Points
[:, :, 1]
        10   20   30  40
  'a'  -11    8   -7   2
  'b'    2  -12  -12   1
  'c'   -5  -12    2  -2
  'd'   -6    3    3  -7
[and 3 more slices...]

julia> dims(da)
X Categorical{Char} 'a':1:'d' ForwardOrdered,
Y Sampled{Int64} 10:10:40 ForwardOrdered Regular Points,
Ti Sampled{Int64} 1:4 ForwardOrdered Regular Points

julia> @inferred dims(da, (1,))
ERROR: return type Tuple{X{DimensionalData.Dimensions.LookupArrays.Categorical{Char, StepRange{Char, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}} does not match inferred return type Union{Tuple{Ti{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Tuple{X{DimensionalData.Dimensions.LookupArrays.Categorical{Char, StepRange{Char, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Tuple{Y{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, StepRange{Int64, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}}
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[69]:1
```

**Comment by ParadaCarleton** [comment]
Not unique to `Char`. It seems to happen any time the array's axes have different types, which makes sense and is exactly what I'd expect. The weird thing for me is `slicedims` is type-stable:
```
julia> @inferred first(DD.slicedims(da, (1,)))
Y Sampled{Int64} 10:10:40 ForwardOrdered Regular Points,
Ti Sampled{Int64} 1:4 ForwardOrdered Regular Points

julia> @inferred last(DD.slicedims(da, (1,)))
X Categorical{Symbol} Symbol[a] ForwardOrdered
```
So it must be possible to make `dims` type-stable.

**Comment by sethaxen** [comment]
```julia
> julia> @inferred dims(da, (:X,))
> ERROR: return type Tuple{X{DimensionalData.Dimensions.LookupArrays.Categorical{Char, StepRange{Char, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}} does not match inferred return type Any
> Stacktrace:
>  [1] error(s::String)
>    @ Base ./error.jl:35
>  [2] top-level scope
>    @ REPL[71]:1
```

To me it makes sense this is type-unstable because Julia can't infer from a symbol of type `Symbol` which dimensions are meant. What's surprising to me is this:

```julia
julia> @inferred Dimensions.dims(da, X)
X Categorical{Char} ForwardOrdered
wrapping: 'a':1:'d'

julia> @inferred Dimensions.dims(da, (X,))   # has as much type information as the previous case
ERROR: return type Tuple{X{DimensionalData.Dimensions.LookupArrays.Categorical{Char, StepRange{Char, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}} does not match inferred return type Any
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[82]:1
```

**Comment by ParadaCarleton** [comment]
Right. So the weirdness is with the inconsistent pattern of type stability, rather than with `dims` itself being unstable (which I think is reasonable, although maybe using `Base.@constprop :aggressive` would help).

I'll open a separate issue for this.

**Comment by rafaqz** [comment]
Yeah,  `Symbol` is the problem. Although in a lot of cases it will actually constant propagate and be fine. So 
`Profileview.@profview` on some real code is normally better than `@inferred`  for these tests.

If you want to guarantee that everything to always compile away use `Dim{:x}()` objects or `X()`/`Y()`. The other syntax is just nicer for users in the REPL.

And @sethaxen a `Tuple` of `Type`  is inherently type unstable. This isn't a DimensionalData.jl thing but a Julia thing:

```julia
julia> typeof((X, Y))
Tuple{UnionAll, UnionAll}
```

**Comment by rafaqz** [comment]
Just to demonstrate what I mean about `@inferred` not reflecting the real type stability, if you wrap those calls in a function they all compile away,  mostly because of this horrible code in primitives.jl https://github.com/rafaqz/DimensionalData.jl/blob/main/src/Dimensions/primitives.jl#L616-L629

```julia
julia> f1(a) = dims(a, (:X, :Y))
f1 (generic function with 1 method)

julia> f2(a) = dims(a, :X)
f2 (generic function with 1 method)

julia> f3(a) = dims(a, (X, Y))
f3 (generic function with 1 method)

julia> f4(a) = dims(a, X)
f4 (generic function with 1 method)

julia>

julia> @inferred dims(a, (:X, :Y))
ERROR: return type Tuple{X{DimensionalData.Dimensions.LookupArrays.Categorical{Char, StepRange{Char, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoM
etadata}}, Y{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, StepRange{Int64, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, Dim
ensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}} does not match inferred return type Any
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[91]:1

julia> @inferred dims(a, :X)
ERROR: return type X{DimensionalData.Dimensions.LookupArrays.Categorical{Char, StepRange{Char, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadat
a}} does not match inferred return type Any
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[92]:1

julia> @inferred dims(a, X)
X Categorical{Char} ForwardOrdered
wrapping: 'a':1:'d'

julia> @inferred dims(a, (X, Y))
ERROR: return type Tuple{X{DimensionalData.Dimensions.LookupArrays.Categorical{Char, StepRange{Char, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoM
etadata}}, Y{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, StepRange{Int64, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, Dim
ensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}} does not match inferred return type Any
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[94]:1

julia>

julia> @inferred f1(a)
X Categorical{Char} 'a':1:'d' ForwardOrdered,
Y Sampled{Int64} 10:10:40 ForwardOrdered Regular Points

julia> @inferred f2(a)
X Categorical{Char} ForwardOrdered
wrapping: 'a':1:'d'

julia> @inferred f3(a)
X Categorical{Char} 'a':1:'d' ForwardOrdered,
Y Sampled{Int64} 10:10:40 ForwardOrdered Regular Points

julia> @inferred f4(a)
X Categorical{Char} ForwardOrdered
wrapping: 'a':1:'d'

```


Also if you weren't aware, just using `rand` on your dims is possible for you MWE above:

```julia
julia> a = rand(x, y, ti)
4×4×4 DimArray{Float64,3} with dimensions:
  X Categorical{Char} 'a':1:'d' ForwardOrdered,
  Y Sampled{Int64} 10:10:40 ForwardOrdered Regular Points,
  Ti Sampled{Int64} 1:4 ForwardOrdered Regular Points
[:, :, 1]
       10         20          30          40
  'a'   0.141637   0.166278    0.0467329   0.173502
  'b'   0.72958    0.635099    0.931134    0.616241
  'c'   0.435458   0.0410302   0.599964    0.451108
  'd'   0.531967   0.139136    0.800608    0.32238
[and 3 more slices...]
```

**Comment by sethaxen** [comment]
This was superseded by #462

**Pull request closed without merging**
