### PR TITLE
fixes series and updates Makie compat to latest

### PR DESCRIPTION
**Pull request by lazarusA**
this should close https://github.com/rafaqz/DimensionalData.jl/pull/710, https://github.com/rafaqz/DimensionalData.jl/issues/552

### CODE REVIEW

**Comment by rafaqz** [comment]
Something has changed in `rainclouds` too I guess

**Comment by lazarusA** [comment]
volumeslices and series are special cases. They don't fit into the current workflow, since series takes an input a matrix (which usually is assigned to a surface-like call, but now it needs to be a point-like one) and `volumeslices` is actually a `heatmap` call and not a `volume` one.  This hasn't been supported so far. Hence I think we should move with this and open two specific issues for these uses cases.

**Comment by rafaqz** [comment]
Is this good to go?

**Comment by lazarusA** [comment]
Series mutation  method is not supported.  The rest should be fine.

**Comment by rafaqz** [comment]
Is there something that can be done to fix it? Or should I just merge

**Pull request merged**
