### PR TITLE
add more plot recipes

### PR DESCRIPTION
**Pull request by jw3126**
```julia
using Plots
using DimensionalData: X,Y,DimensionalArray

xs = -1:0.1:2
ys = -2:0.1:5
data = [sin(x^2 + y^2) for x in xs, y in ys]
darr = DimensionalArray(data, (X(xs), Y(ys)))
plot(
    heatmap(darr),
    contour(darr),
    surface(darr),
    wireframe(darr),
)
```
grafik

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks! Plot recipes do need a bit more love.

This should be available in 0.4.2 in a few hours.

**Comment by jw3126** [comment]
Cool, thanks for quick merge + release!

**Comment by rafaqz** [comment]
I'm thinking we should change how this works a little. If the actual `X()` and `Y()` dims are used we should reorder them to match Plots.jl x/y order. Otherwise it will plot as currently. Does that make sense?

**Comment by jw3126** [comment]
Ok we can do that. Or should we always transpose? I think there is no right  way to do this, just wrong ones.

**Comment by rafaqz** [comment]
What do you mean exactly? I'm suggesting we do:

```julia
permutedims(A, (X, Y))
```

If the dims are Y, X. We should probably also put `Time` on the x axis if it exists and `X` doesn't. I'm just hoping that most of the time the plots are sensible, but you are right there is not real correct answer.

**Comment by jw3126** [comment]
Really I think this is an unfortunate design decision in `Plots.jl`. There are a couple of desirable properties and we can't have them all:

1. It would be nice if `heatmap(dimarray)` and `heatmap(parent(dimarray))` would look the same (current situation) and not transposed
2. It would be nice if the `X` axis is the `x` axis in the plot and the `Y` axis is the `y` axis in the plot.

We have to violate one, but I don't care much about which one. I am fine with your suggestion.

**Comment by rafaqz** [comment]
Ok that makes sense. I was figuring that the utility of arbitrary dim ordering is automatic permutation. This is important in GeoData.jl where there is one right way to show a map, but at least 4 ways of organising the data - it often has to be reversed as well as permuted. This might be less common with other types of data, I guess thatp most of the dimension and grid operations here will be overkill in other fields.

**Pull request merged**
