### PR TITLE
Add `mergedims`

### LINKED ISSUE #383: Creating a new array with stacked dimensions
Is there a function in this package like [`xarray.DataArray.stack`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.stack.html), where a subset of dimensions are specified, and these dimensions are stacked to create a new dimension, with the data using this new stacked dimension returned?

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes #383.

### CODE REVIEW

**Comment by sethaxen** [comment]
Still a number of cases to handle and tests to add, and the code can probably be simplified, but here's a quick demo so far:

```julia
julia> da = DimArray(randn(2, 3, 4), (X([:a, :b]), Y(0:2), Z));

julia> mergedims(da, Z => :z, (X, Y) => :xy)
4×6 DimArray{Float64,2} with dimensions: 
  Dim{:z} MergedLookup{Tuple{Int64}} Tuple{Int64}[(1,), (2,), (3,), (4,)] Z,
  Dim{:xy} MergedLookup{Tuple{Symbol, Int64}} Tuple{Symbol, Int64}[(:a, 0), (:b, 0), …, (:a, 2), (:b, 2)] X, Y
          (:a, 0)     (:b, 0)    (:a, 1)     (:b, 1)     (:a, 2)    (:b, 2)
  (1,)  -0.234732    0.937741  -1.56803     0.514567    0.943423   0.340649
  (2,)  -0.0977759   2.71815   -0.0940511   0.0488348   0.607243   0.545178
  (3,)  -1.55356     0.538964   1.44391     0.0813604  -1.23244   -1.88348
  (4,)  -0.916037   -0.148356   1.39924    -1.87068    -0.953741   0.111657

julia> ds = DimStack((
           x=DimArray(randn(2, 3, 4), (X([:x1, :x2]), Y(1:3), Z)),
           y=DimArray(randn(2, 3, 4, 5), (X([:x1, :x2]), Y(1:3), Z, Ti)),
           z=DimArray(randn(5), Ti),
       ));

julia> mergedims(ds, (X, Y, Z) => :coord)
DimStack with dimensions: 
  Dim{:coord} MergedLookup{Tuple{Symbol, Int64, Int64}} Tuple{Symbol, Int64, Int64}[(:x1, 1, 1), (:x2, 1, 1), …, (:x1, 3, 4), (:x2, 3, 4)] X, Y, Z,
  Ti
and 3 layers:
  :x Float64 dims: Dim{:coord} (24)
  :y Float64 dims: Ti, Dim{:coord} (5×24)
  :z Float64 dims: Ti (5)
```

**Comment by rafaqz** [comment]
Hah I thought we had already added this 😅

**Comment by sethaxen** [comment]
> Hah I thought we had already added this sweat_smile

Yeah you did the hard work with `MergedLookup`, and I've been dragging my heels on this because my attempts have been pretty ugly.

Now that I think about this, I think something more powerful than `mergedims` would be `replacedims`. Here's an example how this would be used:

```julia
julia> da = DimArray(randn(2, 3, 4), (X([:a, :b]), Y(0:2), Z));

julia> da2 = replacedims(da, (X, Y) => :xy)  # specifying just a symbol or a `Dim{:xy}(NoLookup())` builds a `MergedLookup`
4×6 DimArray{Float64,2} with dimensions: 
  Z,
  Dim{:xy} MergedLookup{Tuple{Symbol, Int64}} Tuple{Symbol, Int64}[(:a, 0), (:b, 0), …, (:a, 2), (:b, 2)] X, Y
   (:a, 0)    (:b, 0)     (:a, 1)    (:b, 1)   (:a, 2)      (:b, 2)
  1.32582    0.0397176   0.119409   0.370466  0.607889     0.215393
  1.04292    0.580848   -2.50421   -0.427551  0.00542122   1.46283
 -0.781961  -0.210792   -0.14273   -0.347183  1.16847     -0.662832
 -0.391376   1.02454     2.76603   -0.209639  0.0464564   -1.47592

julia> replacedims(da, (X, Y) => Dim{:xy}(0:5))  # but a dimension with a lookup causes that lookup to be used instead
4×6 DimArray{Float64,2} with dimensions: 
  Z,
  Dim{:xy} Sampled{Int64} 0:5 ForwardOrdered Regular Points
  0          1           2          3         4            5
  1.32582    0.0397176   0.119409   0.370466  0.607889     0.215393
  1.04292    0.580848   -2.50421   -0.427551  0.00542122   1.46283
 -0.781961  -0.210792   -0.14273   -0.347183  1.16847     -0.662832
 -0.391376   1.02454     2.76603   -0.209639  0.0464564   -1.47592

julia> replacedims(da2, :xy => dims(da, (X, Y)), Z => :z)  # no `unmergedims` necessary!
4×2×3 DimArray{Float64,3} with dimensions: 
  Dim{:z},
  X Categorical{Symbol} Symbol[:a, :b] ForwardOrdered,
  Y Sampled{Int64} 0:2 ForwardOrdered Regular Points
[:, :, 1]
   :a         :b
  1.32582    0.0397176
  1.04292    0.580848
 -0.781961  -0.210792
 -0.391376   1.02454
[and 2 more slices...]
```

As a bonus, `replacedims` has a syntax very similar to `replace`, in that it takes pairs and ignores pairs that don't apply.

The one thing I'm not quite satisfied with is how the user specifies to use or not to use a `MergedLookup`. What do you think?

**Comment by rafaqz** [comment]
Can we also use `replacedims` for just replacing individual dimensions if you pass a dim/type/symbol instead of a tuple?

From the name it seems like you would be able to do that, and feels pretty powerful if it does all these things.

It can also use the machinery of `set` to fill in missing detail in the passed in dimensions.

`swapdims` etc primitives were always a bit low level for direct use.

**Comment by rafaqz** [comment]
Sorry didny mean to mark as ready for review, im on a phone.

**Comment by sethaxen** [comment]
> Can we also use `replacedims` for just replacing individual dimensions if you pass a dim/type/symbol instead of a tuple?

Yes that's the idea (e.g. the final example). 

> It can also use the machinery of `set` to fill in missing detail in the passed in dimensions.

I think this makes sense for `set` to be used within the function, but I don't think it should support e.g. the user providing a pair `Dim{:z} => 1:4`, since `set` already covers that. `replacedims` would completely swap out one or more dimensions.

> `swapdims` etc primitives were always a bit low level for direct use.

Agreed, yes, I hadn't found a way to do this easily with the existing primitives.

**Comment by rafaqz** [comment]
Yeah makes sense. I has to be a dim, but we can fill in auto fields.

I want to rename `set` to `setdims` too, as thats mostly what it does. I think this could be a good combo of functions.

**Comment by sethaxen** [comment]
> I want to rename `set` to `setdims` too, as thats mostly what it does.

Yeah `set` is too vague and too likely to collide with other packages. However, `setdims` may give the impression that you're setting the dims themselves, but you're actually setting properties of the dims. What about something like `setdimproperties`?

**Comment by rafaqz** [comment]
Yeah thats better. I wrote all these terse function names like `set` and ` format` that in retrosoect are just vague.

It should also be `formatlookups`.

**Comment by rafaqz** [comment]
Closed, incorporated in #536

**Pull request closed without merging**
