### PR TITLE
Documentation!

### PR DESCRIPTION
**Pull request by Datseris**
Alright, here is a first draft that will hopefully organize things more, to make everything more discoverable. There are some things I can't write, because I really know almost nothing about...

A point I must raise: I am of the school of thought that the README should not display a full stack of documentation, because in my eyes it has several drawbacks:
1. very hard to maintain, something will be forgotten
2. twice as much documentation to write, as it has to be written in two places
3. invites lazy behavior: if there is some info some people (guilty!) won't look at the docs!

### CODE REVIEW

**Comment by Datseris** [comment]
@rafaqz I really urge you to re-think what is exported here. To make the docs runnable I've added some export statements, but I think the current export situation doesn't make sense. 

You are currently exporting many names like:
```julia
export Sampling, SingleSample, MultiSample, UnknownSampling

export Order, Ordered, Unordered

export Grid, UnknownGrid

export AbstractCategoricalGrid, CategoricalGrid

export IndependentGrid, AbstractAlignedGrid, AlignedGrid, BoundedGrid, RegularGrid

export DependentGrid, TransformedGrid
```
which I am skeptical of how much use are to a front-end user, but I am also not that familiar with grids so I might be wrong.

Meanwhile some definitely useful names directly related with the core functionality are not exported, like:
```
export X, Y, Z, Time, @dim, hasdim, dimnum, dims2indices
```

Whether you want some "standarized" names of dimensions like `X, Y, Time` to exist or not can be discussed, but if they do exist, they should be exported. If not, the documentation examples should start by creating the dimensions from scratch. Either way is fine for me, but I think only one of the two should be done for clarity.

**Comment by rafaqz** [comment]
If you ever need to construct grids manually you will need those grid types. But I'm not sure if that means they should be exported.

`@dim` shouldn't be exported yet, lets make it a little harder to find for now.

`haddim` and `dimnum` absolutely should be exported.

`Time` can't be exported or it will clash all the time with Dates and give a warning.

Maybe `X`, `Y`, `Z`, and `Ti` should be exported.

**Comment by rafaqz** [comment]
Thanks for getting this organised! I'll start thinking about documenting grids.

FYI `refdims` is just a record of the point in some dimension that the current array was sliced from. So if you slice a time sequence they retain the point they were sliced from so you can show it on a plot label. And you will be able to use `cat` to put them back together correctly, when I write that code.

**Comment by Datseris** [comment]
> @dim shouldn't be exported yet, lets make it a little harder to find for now.
> Maybe `X, Y, Z`, and `Ti` should be exported.

What is the argument for not being able to make your own dimensions?

In fact, if neither `X, Y,` etc. or `@dims` are exported, then there is no public API with which to use DimensionalData.jl. 100% of the functionality relies on having a `DimensionalArray`. And it seems to me so far that the only way to get a `DimensionalArray` is to have a dimension. So if there is no public API to create a dimension, how do you even make a `DimensionalArray`?

Using another package that gives you `DimensionalArray` is not a good argument, because some people want minimum amount of dependencies. So I'd say, give the power to the people. 

Having arrays with dimensions by itself is powerful, and some may want to use _just that_. Not coupling with metadata, not pre-defined dimensions, not plotting, not GeoData.jl, just good old Julia arrays with named dimensions. That's why something like DimensionalData.jl should have a concrete way to use 100% of its functionality freely. And that summarizes why I think that the support on making your own dimension should be public.

**Comment by rafaqz** [comment]
I do get your point, I was already agreeing with you on half those points. X, Y, Z were not public because they are small types and may clash with existing things. But lets export them, just not `Time`. We'll export `Ti` instead.

The problem with using `@dims` as it currently stands is that you lose the ability to use plot recipes. I just want to get @dims right before we encourage rampant creation of new dims. Fixing #34 will deal with this to some extent.

**Comment by dims** [comment]
hi @rafaqz !

**Comment by Datseris** [comment]
hahaha :P 

Alright. I will modify this later on to export `X,...Ti` and wait for `@dims`. I use `@dims` in my own work so it has seen some testing, but lets wait for #34 as you said so that `@dims` can define subtypes of abstract types.

**Comment by Datseris** [comment]
Alright @rafaqz this is good to review and merge. A point I want to raise again: I am of the school of thought that the README should not display a full stack of documentation, because in my eyes it has several drawbacks:
1. very hard to maintain, something will be forgotten
2. twice as much documentation to write, as it has to be written in two places
3. invites lazy behavior: if there is some info some people (guilty!) won't look at the docs!

**Comment by rafaqz** [comment]
I agree. The readme was more of a mission statement I banged out for when the axisarrays discussion was happening. But if you check my other packages like DynamicGrids you'll see a trick for using the readme as the module doc, which is is a good compromise. An empty readme isnt very useful either.

**Comment by rafaqz** [comment]
Thanks for getting this finished I will try to go over this and edit it some time this week.

**Comment by Datseris** [comment]
@rafaqz new features are being added here, e.g. the abstract dimension dispatch like `XDim`, but they are not added in the documentation. If you merge this it will be possible and straight forward to document a new PR directly in the hosted docs. If you have a look at https://github.com/JuliaDynamics/DrWatson.jl/pull/125 , it is in fact even possible to preview documentation changes in PRs now.

Long story made short: the sooner this PR is merged, the less effort we would have to spend to modify it and add new documentation.

**Comment by rafaqz** [comment]
Yeah I know. It's just that there is just a bunch for me to do in there and read over, and it's not immediately useful to me so it loses out in the 10 package triage I do day-to-day right now (lol).

But I'll do it this week, don't worry. Good to know you can preview them too.

**Comment by Datseris** [comment]
@rafaqz can you please merge this? Holding it back more will make things much harder to document later on... Let's have a starting point somewhere so that each PR can be documented on its own PR instead of having to keep track of several undocumented things. I unfortunately have to admit that I have lost track of all the things that should be added here. I intended to update this PR with recent changes, but there were so many of them it is not possible anymore.

Require every new PR to add a documentation about the PR is a simple way, head-ache free way to have a well documented code.

I am holding back opening 2 PRs because this is unmerged. (I will continue to hold them back until this is merged)

**Comment by rafaqz** [comment]
Sorry!!! These last two weeks have been too busy, I just did a 13 hour day of modelling and I haven't finished yet...

I'm struggling to find the time to read over this and it needs a good hour or so to get right, and it will need actual edits from me. With the other PRs I can just trust the tests. But I hope to get it done before monday.

**Comment by rafaqz** [comment]
Closed in favour of #86, with some edits and updates

**Pull request closed without merging**
